### ISSUE TITLE
File permissions rules that look for exact permissions are currently implemented wrongfully

### ISSUE THREAD

**Issue by jeniawhite** [elastic/csp-security-policies#132]
The current implementation that we have for the file permissions checks is implemented with maximum permissions.
This means that we verify that the permissions are equal or more restrictive.
Yet, we have a single rule **1.1.21** in the Kubernetes benchmark that goes by the name **"Ensure that the Kubernetes PKI key file permissions are set to 600 (Manual)"**.
This rule wants to verify that the permissions are exactly 600 and not more restrictive like all of the other rules.
This means that we aren't compliant with this rule and evaluate the resources incorrectly.
Our code right now will pass any permission that is more restrictive than 600.

**Comment by tinnytintin10** [comment]
Thanks for pointing this out, Jenia! 

Could there be any unintended outcomes bc of the striceter file permissions in this case? I am guessing there is because they left out the "....or more restrictive" part that they include on other file permissions rules. 

Either way, we're not evaluating the rule according to the benchmark specification, so it's worth fixing; just checking on impact so we know how to prioritize. 

cc @oren-zohar
