### ISSUE TITLE
[CIS GCP] Implement the remaining rules

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#305]
### Definition of done
Implement all the remaining automated rules or provide a decent explanation why a rule can not be implemented.

- [x] 2.1 Ensure That Cloud Audit Logging Is Configured Properly
- [x] 2.2 Ensure That Sinks Are Configured for All Log Entries
- [x] 2.12 Ensure That Cloud DNS Logging Is Enabled for All VPC Networks
- [x] 2.13 Ensure Cloud Asset Inventory Is Enabled
- [x] 3.2 Ensure Legacy Networks Do Not Exist for Older Projects

**Comment by uri-weisman** [comment]
Rules that are complex to implement: 

- Rule 1.16
  - Asset type is not supported by GCP's asset inventory and seems to be applied only for Orgs.
- Rule 2.1
  - Rule applies at all scopes, org, folder and project. if the setting is enabled for a folder is will apply for all projects within the folder, however, it won't be shown in the project's config.


  > Note that projects inherit settings from folders, which in turn inherit settings from the organization. When called, projects get-iam-policy, the result shows only the policies set in the project, not the policies inherited from the parent folder or organization. Nevertheless, if the parent folder has Cloud Audit Logging enabled, the project does as well.


- Rule 2.2 
   -  requires evaluating all sinks and ensuring at least 1 has an empty filter:
  > Ensure there is at least one sink with an empty Inclusion filter.
  
     and we currently send each sink as an asset, will require an additional fetcher. 
   - also requires checking each sink's `destination` (usually a bucket) actually exists, which i guess means making an http request which would be new to our rego policies and probably not something we'd like to do. 


- Rule 2.12 
    - requires two resources for evaluation, ensure that every VPC has a dns policy with logging enabled, will result with an additional fetcher.

- Rule 2.13
  - This rule will always result with `true` because we enable the asset inventory service, however, we need to pass a list `serviceusage.googleapis.com/Service` to verify that the asset inventory is among the enabled services.
- Rule 2.15
  - Asset type, `accessapproval.googleapis.com`, is not supported by the asset inventory.
- Rule 3.2 
   - impossible to verify, legacy networks are deprecated and can not be created.

**Comment by tinnytintin10** [comment]
@uri-weisman If it helps, let's prioritize the rules in the following order:

1. Potential Impact: What could go wrong if the rule is not implemented?
2. Likelihood: How likely is it that a security incident could occur due to non-compliance?
3. Industry Best Practices: How does this rule align with general security best practices?

Based on these factors, here's how I would prioritize the rules:

1. **2.1 Ensure That Cloud Audit Logging Is Configured Properly**: 
   - **Potential Impact**: High. Without proper logging, detecting and investigating security incidents becomes difficult.
   - **Likelihood**: High. Logging is fundamental to security monitoring.
   - **Industry Best Practices**: Essential for any security compliance.

2. **2.15 Ensure 'Access Approval' is 'Enabled'**: 
   - **Potential Impact**: High. Unauthorized access could lead to data breaches.
   - **Likelihood**: Medium. Depends on internal controls.
   - **Industry Best Practices**: Strongly recommended for sensitive or critical resources.

3. **2.2 Ensure That Sinks Are Configured for All Log Entries**: 
   - **Potential Impact**: Medium. Without centralized logging, monitoring can be inconsistent.
   - **Likelihood**: Medium. Centralized logging is commonly recommended.
   - **Industry Best Practices**: Important for effective monitoring.

4. **2.12 Ensure That Cloud DNS Logging Is Enabled for All VPC Networks**: 
   - **Potential Impact**: Medium. DNS logs can reveal malicious activity.
   - **Likelihood**: Medium. DNS attacks are common.
   - **Industry Best Practices**: Recommended for advanced threat detection.

5. **2.13 Ensure Cloud Asset Inventory Is Enabled**: 
   - **Potential Impact**: Medium. Lack of inventory can lead to poor governance.
   - **Likelihood**: Low. Direct impact is less immediate.
   - **Industry Best Practices**: Important for governance and risk management.

6. **1.16 Ensure Essential Contacts is Configured for Organization**: 
   - **Potential Impact**: Low. Mainly affects communication.
   - **Likelihood**: Low. Not directly related to security incidents.
   - **Industry Best Practices**: Good to have for administrative purposes.

7. **3.2 Ensure Legacy Networks Do Not Exist for Older Projects**: 
   - **Potential Impact**: Low. Affects only older projects.
   - **Likelihood**: Low. Older projects are less likely to be in active use.
   - **Industry Best Practices**: Good to clean up but not urgent.

**Comment by uri-weisman** [comment]
As agreed with @tinnytintin10 

Rules 2.1 and 2.2 will be implemented only for the org level, in order to avoid false positives for the project scope.
Rules 1.16 and 2.15 will not be implemented as they are low-priority rules and are not supported by the asset inventory.

Editing DOD.
